language: go

addons:
  ssh_known_hosts: home199125616.1and1-data.host
  apt:
    packages:
      - lftp
go:
  - master

install:
  - go get github.com/spf13/hugo

script:
  - hugo -b http://longmeadow-church.org.uk/ --canonifyURLs

after_success:
  if ([ "$TRAVIS_PULL_REQUEST" == "false"] && [ "$TRAVIS_BRANCH" == "master" ]); then
    "lftp -u ${FTP_USER},${FTP_PASSWORD} -e 'mirror --reverse public/ /;exit' sftp://home199125616.1and1-data.host"
  else
    echo "Pull request or branch other than master. Not deploying"
  fi
notifications:
  email:
    on_failure: always
